/*
 * generated by Xtext
 */
package org.nightlabs.vestigo.xtext.jdoql;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JDOQLRuntimeModule extends org.nightlabs.vestigo.xtext.jdoql.AbstractJDOQLRuntimeModule {

}
