
package org.nightlabs.jjqb.core.licence.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Passport", targetNamespace = "http://www.payproglobal.com/", wsdlLocation = "https://www.payproglobal.com/passport/Service.asmx?WSDL")
public class Passport
    extends Service
{

    private final static URL PASSPORT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.nightlabs.jjqb.core.licence.ws.Passport.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.nightlabs.jjqb.core.licence.ws.Passport.class.getResource(".");
            url = new URL(baseUrl, "https://www.payproglobal.com/passport/Service.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://www.payproglobal.com/passport/Service.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PASSPORT_WSDL_LOCATION = url;
    }

    public Passport(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Passport() {
        super(PASSPORT_WSDL_LOCATION, new QName("http://www.payproglobal.com/", "Passport"));
    }

    /**
     * 
     * @return
     *     returns PassportSoap
     */
    @WebEndpoint(name = "PassportSoap")
    public PassportSoap getPassportSoap() {
        return super.getPort(new QName("http://www.payproglobal.com/", "PassportSoap"), PassportSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PassportSoap
     */
    @WebEndpoint(name = "PassportSoap")
    public PassportSoap getPassportSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.payproglobal.com/", "PassportSoap"), PassportSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PassportSoap
     */
    @WebEndpoint(name = "PassportSoap12")
    public PassportSoap getPassportSoap12() {
        return super.getPort(new QName("http://www.payproglobal.com/", "PassportSoap12"), PassportSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PassportSoap
     */
    @WebEndpoint(name = "PassportSoap12")
    public PassportSoap getPassportSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.payproglobal.com/", "PassportSoap12"), PassportSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PassportHttpGet
     */
    @WebEndpoint(name = "PassportHttpGet")
    public PassportHttpGet getPassportHttpGet() {
        return super.getPort(new QName("http://www.payproglobal.com/", "PassportHttpGet"), PassportHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PassportHttpGet
     */
    @WebEndpoint(name = "PassportHttpGet")
    public PassportHttpGet getPassportHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.payproglobal.com/", "PassportHttpGet"), PassportHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns PassportHttpPost
     */
    @WebEndpoint(name = "PassportHttpPost")
    public PassportHttpPost getPassportHttpPost() {
        return super.getPort(new QName("http://www.payproglobal.com/", "PassportHttpPost"), PassportHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PassportHttpPost
     */
    @WebEndpoint(name = "PassportHttpPost")
    public PassportHttpPost getPassportHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.payproglobal.com/", "PassportHttpPost"), PassportHttpPost.class, features);
    }

}
