
package org.nightlabs.jjqb.core.licence.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PassportSoap", targetNamespace = "http://www.payproglobal.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PassportSoap {


    /**
     * Gets information about an activation key
     * 
     * @param activationKey
     * @param customerEmail
     * @param productID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateLicense", action = "http://www.payproglobal.com/ValidateLicense")
    @WebResult(name = "ValidateLicenseResult", targetNamespace = "http://www.payproglobal.com/")
    @RequestWrapper(localName = "ValidateLicense", targetNamespace = "http://www.payproglobal.com/", className = "org.nightlabs.jjqb.core.licence.ws.ValidateLicense")
    @ResponseWrapper(localName = "ValidateLicenseResponse", targetNamespace = "http://www.payproglobal.com/", className = "org.nightlabs.jjqb.core.licence.ws.ValidateLicenseResponse")
    public String validateLicense(
        @WebParam(name = "ProductID", targetNamespace = "http://www.payproglobal.com/")
        int productID,
        @WebParam(name = "CustomerEmail", targetNamespace = "http://www.payproglobal.com/")
        String customerEmail,
        @WebParam(name = "ActivationKey", targetNamespace = "http://www.payproglobal.com/")
        String activationKey);

    /**
     * Activates an activation key
     * 
     * @param activationKey
     * @param customerEmail
     * @param productID
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ActiveLicense", action = "http://www.payproglobal.com/ActiveLicense")
    @WebResult(name = "ActiveLicenseResult", targetNamespace = "http://www.payproglobal.com/")
    @RequestWrapper(localName = "ActiveLicense", targetNamespace = "http://www.payproglobal.com/", className = "org.nightlabs.jjqb.core.licence.ws.ActiveLicense")
    @ResponseWrapper(localName = "ActiveLicenseResponse", targetNamespace = "http://www.payproglobal.com/", className = "org.nightlabs.jjqb.core.licence.ws.ActiveLicenseResponse")
    public boolean activeLicense(
        @WebParam(name = "ProductID", targetNamespace = "http://www.payproglobal.com/")
        int productID,
        @WebParam(name = "CustomerEmail", targetNamespace = "http://www.payproglobal.com/")
        String customerEmail,
        @WebParam(name = "ActivationKey", targetNamespace = "http://www.payproglobal.com/")
        String activationKey);

}
