/*
* generated by Xtext
*/
package org.nightlabs.jjqb.xtext.jpql.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JPQLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/nightlabs/jjqb/xtext/jpql/parser/antlr/internal/InternalJPQL.tokens");
	}
}
