/*
* generated by Xtext
*/
package org.nightlabs.jjqb.xtext.jdoql.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JDOQLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/nightlabs/jjqb/xtext/jdoql/parser/antlr/internal/InternalJDOQLParser.tokens");
	}
}
