/*
 * generated by Xtext
 */
package org.nightlabs.vestigo.xtext.jpql;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JPQLRuntimeModule extends org.nightlabs.vestigo.xtext.jpql.AbstractJPQLRuntimeModule {

}
