/*
* generated by Xtext
*/
package org.nightlabs.vestigo.xtext.jdoql.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.nightlabs.vestigo.xtext.jdoql.services.JDOQLGrammarAccess;

public class JDOQLParser extends AbstractContentAssistParser {
	
	@Inject
	private JDOQLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.nightlabs.vestigo.xtext.jdoql.ui.contentassist.antlr.internal.InternalJDOQLParser createParser() {
		org.nightlabs.vestigo.xtext.jdoql.ui.contentassist.antlr.internal.InternalJDOQLParser result = new org.nightlabs.vestigo.xtext.jdoql.ui.contentassist.antlr.internal.InternalJDOQLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSubqueryFromClauseAccess().getAlternatives_1(), "rule__SubqueryFromClause__Alternatives_1");
					put(grammarAccess.getUnaryExpressionAccess().getAlternatives(), "rule__UnaryExpression__Alternatives");
					put(grammarAccess.getFieldAccessExpressionAccess().getAlternatives(), "rule__FieldAccessExpression__Alternatives");
					put(grammarAccess.getParameterOrFieldOrMethodExpressionAccess().getAlternatives(), "rule__ParameterOrFieldOrMethodExpression__Alternatives");
					put(grammarAccess.getFieldOrMethodExpressionAccess().getAlternatives(), "rule__FieldOrMethodExpression__Alternatives");
					put(grammarAccess.getStaticMethodExpressionAccess().getAlternatives(), "rule__StaticMethodExpression__Alternatives");
					put(grammarAccess.getMethodExpressionAccess().getAlternatives(), "rule__MethodExpression__Alternatives");
					put(grammarAccess.getParenthesesExpressionAccess().getAlternatives_1(), "rule__ParenthesesExpression__Alternatives_1");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getPrimitiveTypeAccess().getAlternatives(), "rule__PrimitiveType__Alternatives");
					put(grammarAccess.getNumericTypeAccess().getAlternatives(), "rule__NumericType__Alternatives");
					put(grammarAccess.getIntegralTypeAccess().getAlternatives(), "rule__IntegralType__Alternatives");
					put(grammarAccess.getFloatingPointTypeAccess().getAlternatives(), "rule__FloatingPointType__Alternatives");
					put(grammarAccess.getBooleanLiteralAccess().getAlternatives(), "rule__BooleanLiteral__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getQualifiedIdentifierAccess().getAlternatives(), "rule__QualifiedIdentifier__Alternatives");
					put(grammarAccess.getOrderByDirectionAccess().getAlternatives(), "rule__OrderByDirection__Alternatives");
					put(grammarAccess.getUnaryOperatorAccess().getAlternatives(), "rule__UnaryOperator__Alternatives");
					put(grammarAccess.getAdditionOperatorAccess().getAlternatives(), "rule__AdditionOperator__Alternatives");
					put(grammarAccess.getMultiplicationOperatorAccess().getAlternatives(), "rule__MultiplicationOperator__Alternatives");
					put(grammarAccess.getComparisonOperatorAccess().getAlternatives(), "rule__ComparisonOperator__Alternatives");
					put(grammarAccess.getSingleStringJDOQLAccess().getGroup(), "rule__SingleStringJDOQL__Group__0");
					put(grammarAccess.getSubqueryAccess().getGroup(), "rule__Subquery__Group__0");
					put(grammarAccess.getSelectClauseAccess().getGroup(), "rule__SelectClause__Group__0");
					put(grammarAccess.getSubquerySelectClauseAccess().getGroup(), "rule__SubquerySelectClause__Group__0");
					put(grammarAccess.getResultClauseAccess().getGroup(), "rule__ResultClause__Group__0");
					put(grammarAccess.getResultClauseAccess().getGroup_2(), "rule__ResultClause__Group_2__0");
					put(grammarAccess.getSubqueryResultClauseAccess().getGroup(), "rule__SubqueryResultClause__Group__0");
					put(grammarAccess.getIntoClauseAccess().getGroup(), "rule__IntoClause__Group__0");
					put(grammarAccess.getResultSpecAccess().getGroup(), "rule__ResultSpec__Group__0");
					put(grammarAccess.getResultNamingAccess().getGroup(), "rule__ResultNaming__Group__0");
					put(grammarAccess.getFromClauseAccess().getGroup(), "rule__FromClause__Group__0");
					put(grammarAccess.getFromClauseAccess().getGroup_2(), "rule__FromClause__Group_2__0");
					put(grammarAccess.getSubqueryFromClauseAccess().getGroup(), "rule__SubqueryFromClause__Group__0");
					put(grammarAccess.getSubqueryFromClauseAccess().getGroup_1_0(), "rule__SubqueryFromClause__Group_1_0__0");
					put(grammarAccess.getSubqueryFromClauseAccess().getGroup_3(), "rule__SubqueryFromClause__Group_3__0");
					put(grammarAccess.getAliasAccess().getGroup(), "rule__Alias__Group__0");
					put(grammarAccess.getWhereClauseAccess().getGroup(), "rule__WhereClause__Group__0");
					put(grammarAccess.getVariablesClauseAccess().getGroup(), "rule__VariablesClause__Group__0");
					put(grammarAccess.getVariablesClauseAccess().getGroup_2(), "rule__VariablesClause__Group_2__0");
					put(grammarAccess.getVariableDeclarationAccess().getGroup(), "rule__VariableDeclaration__Group__0");
					put(grammarAccess.getParametersClauseAccess().getGroup(), "rule__ParametersClause__Group__0");
					put(grammarAccess.getParametersClauseAccess().getGroup_2(), "rule__ParametersClause__Group_2__0");
					put(grammarAccess.getParameterDeclarationAccess().getGroup(), "rule__ParameterDeclaration__Group__0");
					put(grammarAccess.getImportClauseAccess().getGroup(), "rule__ImportClause__Group__0");
					put(grammarAccess.getImportClauseAccess().getGroup_1(), "rule__ImportClause__Group_1__0");
					put(grammarAccess.getImportDeclarationAccess().getGroup(), "rule__ImportDeclaration__Group__0");
					put(grammarAccess.getGroupByClauseAccess().getGroup(), "rule__GroupByClause__Group__0");
					put(grammarAccess.getGroupByClauseAccess().getGroup_3(), "rule__GroupByClause__Group_3__0");
					put(grammarAccess.getHavingClauseAccess().getGroup(), "rule__HavingClause__Group__0");
					put(grammarAccess.getOrderByClauseAccess().getGroup(), "rule__OrderByClause__Group__0");
					put(grammarAccess.getOrderByClauseAccess().getGroup_3(), "rule__OrderByClause__Group_3__0");
					put(grammarAccess.getOrderBySpecAccess().getGroup(), "rule__OrderBySpec__Group__0");
					put(grammarAccess.getRangeClauseAccess().getGroup(), "rule__RangeClause__Group__0");
					put(grammarAccess.getConditionalOrExpressionAccess().getGroup(), "rule__ConditionalOrExpression__Group__0");
					put(grammarAccess.getConditionalOrExpressionAccess().getGroup_1(), "rule__ConditionalOrExpression__Group_1__0");
					put(grammarAccess.getConditionalAndExpressionAccess().getGroup(), "rule__ConditionalAndExpression__Group__0");
					put(grammarAccess.getConditionalAndExpressionAccess().getGroup_1(), "rule__ConditionalAndExpression__Group_1__0");
					put(grammarAccess.getSimpleOrExpressionAccess().getGroup(), "rule__SimpleOrExpression__Group__0");
					put(grammarAccess.getSimpleOrExpressionAccess().getGroup_1(), "rule__SimpleOrExpression__Group_1__0");
					put(grammarAccess.getSimpleAndExpressionAccess().getGroup(), "rule__SimpleAndExpression__Group__0");
					put(grammarAccess.getSimpleAndExpressionAccess().getGroup_1(), "rule__SimpleAndExpression__Group_1__0");
					put(grammarAccess.getComparisonOperatorExpressionAccess().getGroup(), "rule__ComparisonOperatorExpression__Group__0");
					put(grammarAccess.getComparisonOperatorExpressionAccess().getGroup_1(), "rule__ComparisonOperatorExpression__Group_1__0");
					put(grammarAccess.getAdditionExpressionAccess().getGroup(), "rule__AdditionExpression__Group__0");
					put(grammarAccess.getAdditionExpressionAccess().getGroup_1(), "rule__AdditionExpression__Group_1__0");
					put(grammarAccess.getMultiplicationExpressionAccess().getGroup(), "rule__MultiplicationExpression__Group__0");
					put(grammarAccess.getMultiplicationExpressionAccess().getGroup_1(), "rule__MultiplicationExpression__Group_1__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup_0(), "rule__UnaryExpression__Group_0__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup_1(), "rule__UnaryExpression__Group_1__0");
					put(grammarAccess.getFieldAccessExpressionAccess().getGroup_1(), "rule__FieldAccessExpression__Group_1__0");
					put(grammarAccess.getFieldAccessExpressionAccess().getGroup_1_1(), "rule__FieldAccessExpression__Group_1_1__0");
					put(grammarAccess.getParameterOrFieldOrMethodExpressionAccess().getGroup_3(), "rule__ParameterOrFieldOrMethodExpression__Group_3__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_0(), "rule__StaticMethodExpression__Group_0__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_1(), "rule__StaticMethodExpression__Group_1__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_2(), "rule__StaticMethodExpression__Group_2__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_3(), "rule__StaticMethodExpression__Group_3__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_4(), "rule__StaticMethodExpression__Group_4__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_5(), "rule__StaticMethodExpression__Group_5__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_6(), "rule__StaticMethodExpression__Group_6__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_7(), "rule__StaticMethodExpression__Group_7__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_8(), "rule__StaticMethodExpression__Group_8__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_9(), "rule__StaticMethodExpression__Group_9__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_10(), "rule__StaticMethodExpression__Group_10__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_11(), "rule__StaticMethodExpression__Group_11__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_12(), "rule__StaticMethodExpression__Group_12__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_13(), "rule__StaticMethodExpression__Group_13__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_14(), "rule__StaticMethodExpression__Group_14__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_15(), "rule__StaticMethodExpression__Group_15__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_16(), "rule__StaticMethodExpression__Group_16__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_17(), "rule__StaticMethodExpression__Group_17__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_18(), "rule__StaticMethodExpression__Group_18__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_19(), "rule__StaticMethodExpression__Group_19__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_20(), "rule__StaticMethodExpression__Group_20__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_21(), "rule__StaticMethodExpression__Group_21__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_22(), "rule__StaticMethodExpression__Group_22__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_23(), "rule__StaticMethodExpression__Group_23__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_24(), "rule__StaticMethodExpression__Group_24__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_25(), "rule__StaticMethodExpression__Group_25__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_26(), "rule__StaticMethodExpression__Group_26__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_27(), "rule__StaticMethodExpression__Group_27__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_28(), "rule__StaticMethodExpression__Group_28__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_29(), "rule__StaticMethodExpression__Group_29__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_30(), "rule__StaticMethodExpression__Group_30__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_31(), "rule__StaticMethodExpression__Group_31__0");
					put(grammarAccess.getStaticMethodExpressionAccess().getGroup_32(), "rule__StaticMethodExpression__Group_32__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_0(), "rule__MethodExpression__Group_0__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_1(), "rule__MethodExpression__Group_1__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_2(), "rule__MethodExpression__Group_2__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_3(), "rule__MethodExpression__Group_3__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_4(), "rule__MethodExpression__Group_4__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_5(), "rule__MethodExpression__Group_5__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_6(), "rule__MethodExpression__Group_6__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_7(), "rule__MethodExpression__Group_7__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_8(), "rule__MethodExpression__Group_8__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_9(), "rule__MethodExpression__Group_9__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_10(), "rule__MethodExpression__Group_10__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_11(), "rule__MethodExpression__Group_11__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_11_3(), "rule__MethodExpression__Group_11_3__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_12(), "rule__MethodExpression__Group_12__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_13(), "rule__MethodExpression__Group_13__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_14(), "rule__MethodExpression__Group_14__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_15(), "rule__MethodExpression__Group_15__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_16(), "rule__MethodExpression__Group_16__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_16_3(), "rule__MethodExpression__Group_16_3__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_17(), "rule__MethodExpression__Group_17__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_18(), "rule__MethodExpression__Group_18__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_19(), "rule__MethodExpression__Group_19__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_20(), "rule__MethodExpression__Group_20__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_21(), "rule__MethodExpression__Group_21__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_22(), "rule__MethodExpression__Group_22__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_23(), "rule__MethodExpression__Group_23__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_24(), "rule__MethodExpression__Group_24__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_25(), "rule__MethodExpression__Group_25__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_26(), "rule__MethodExpression__Group_26__0");
					put(grammarAccess.getMethodExpressionAccess().getGroup_27(), "rule__MethodExpression__Group_27__0");
					put(grammarAccess.getParenthesesExpressionAccess().getGroup(), "rule__ParenthesesExpression__Group__0");
					put(grammarAccess.getQualifiedIdentifierAccess().getGroup_9(), "rule__QualifiedIdentifier__Group_9__0");
					put(grammarAccess.getQualifiedIdentifierAccess().getGroup_9_2(), "rule__QualifiedIdentifier__Group_9_2__0");
					put(grammarAccess.getQualifiedIdentifierAccess().getGroup_10(), "rule__QualifiedIdentifier__Group_10__0");
					put(grammarAccess.getQualifiedIdentifierAccess().getGroup_10_2(), "rule__QualifiedIdentifier__Group_10_2__0");
					put(grammarAccess.getQualifiedIdentifierAccess().getGroup_11(), "rule__QualifiedIdentifier__Group_11__0");
					put(grammarAccess.getQualifiedIdentifierAccess().getGroup_11_1(), "rule__QualifiedIdentifier__Group_11_1__0");
					put(grammarAccess.getSingleStringJDOQLAccess().getSelectClauseAssignment_0(), "rule__SingleStringJDOQL__SelectClauseAssignment_0");
					put(grammarAccess.getSingleStringJDOQLAccess().getFromClauseAssignment_1(), "rule__SingleStringJDOQL__FromClauseAssignment_1");
					put(grammarAccess.getSingleStringJDOQLAccess().getWhereClauseAssignment_2(), "rule__SingleStringJDOQL__WhereClauseAssignment_2");
					put(grammarAccess.getSingleStringJDOQLAccess().getVariablesClauseAssignment_3(), "rule__SingleStringJDOQL__VariablesClauseAssignment_3");
					put(grammarAccess.getSingleStringJDOQLAccess().getParametersClauseAssignment_4(), "rule__SingleStringJDOQL__ParametersClauseAssignment_4");
					put(grammarAccess.getSingleStringJDOQLAccess().getImportClauseAssignment_5(), "rule__SingleStringJDOQL__ImportClauseAssignment_5");
					put(grammarAccess.getSingleStringJDOQLAccess().getGroupByClauseAssignment_6(), "rule__SingleStringJDOQL__GroupByClauseAssignment_6");
					put(grammarAccess.getSingleStringJDOQLAccess().getOrderByClauseAssignment_7(), "rule__SingleStringJDOQL__OrderByClauseAssignment_7");
					put(grammarAccess.getSingleStringJDOQLAccess().getRangeClauseAssignment_8(), "rule__SingleStringJDOQL__RangeClauseAssignment_8");
					put(grammarAccess.getSubqueryAccess().getSelectClauseAssignment_0(), "rule__Subquery__SelectClauseAssignment_0");
					put(grammarAccess.getSubqueryAccess().getFromClauseAssignment_1(), "rule__Subquery__FromClauseAssignment_1");
					put(grammarAccess.getSubqueryAccess().getWhereClauseAssignment_2(), "rule__Subquery__WhereClauseAssignment_2");
					put(grammarAccess.getSubqueryAccess().getVariablesClauseAssignment_3(), "rule__Subquery__VariablesClauseAssignment_3");
					put(grammarAccess.getSubqueryAccess().getParametersClauseAssignment_4(), "rule__Subquery__ParametersClauseAssignment_4");
					put(grammarAccess.getSubqueryAccess().getImportClauseAssignment_5(), "rule__Subquery__ImportClauseAssignment_5");
					put(grammarAccess.getSelectClauseAccess().getIsUniqueAssignment_2(), "rule__SelectClause__IsUniqueAssignment_2");
					put(grammarAccess.getSelectClauseAccess().getResultClauseAssignment_3(), "rule__SelectClause__ResultClauseAssignment_3");
					put(grammarAccess.getSelectClauseAccess().getIntoClauseAssignment_4(), "rule__SelectClause__IntoClauseAssignment_4");
					put(grammarAccess.getSubquerySelectClauseAccess().getIsUniqueAssignment_2(), "rule__SubquerySelectClause__IsUniqueAssignment_2");
					put(grammarAccess.getSubquerySelectClauseAccess().getResultClauseAssignment_3(), "rule__SubquerySelectClause__ResultClauseAssignment_3");
					put(grammarAccess.getSubquerySelectClauseAccess().getIntoClauseAssignment_4(), "rule__SubquerySelectClause__IntoClauseAssignment_4");
					put(grammarAccess.getResultClauseAccess().getIsDistinctAssignment_0(), "rule__ResultClause__IsDistinctAssignment_0");
					put(grammarAccess.getResultClauseAccess().getResultSpecsAssignment_1(), "rule__ResultClause__ResultSpecsAssignment_1");
					put(grammarAccess.getResultClauseAccess().getResultSpecsAssignment_2_1(), "rule__ResultClause__ResultSpecsAssignment_2_1");
					put(grammarAccess.getSubqueryResultClauseAccess().getIsDistinctAssignment_0(), "rule__SubqueryResultClause__IsDistinctAssignment_0");
					put(grammarAccess.getSubqueryResultClauseAccess().getResultExpressionAssignment_1(), "rule__SubqueryResultClause__ResultExpressionAssignment_1");
					put(grammarAccess.getIntoClauseAccess().getResultClassNameAssignment_1(), "rule__IntoClause__ResultClassNameAssignment_1");
					put(grammarAccess.getResultSpecAccess().getResultNamingAssignment_1(), "rule__ResultSpec__ResultNamingAssignment_1");
					put(grammarAccess.getResultNamingAccess().getIdentifierAssignment_1(), "rule__ResultNaming__IdentifierAssignment_1");
					put(grammarAccess.getFromClauseAccess().getCandidateClassNameAssignment_1(), "rule__FromClause__CandidateClassNameAssignment_1");
					put(grammarAccess.getFromClauseAccess().getIsExcludeSubclassesAssignment_2_0(), "rule__FromClause__IsExcludeSubclassesAssignment_2_0");
					put(grammarAccess.getSubqueryFromClauseAccess().getFieldAccessExpressionAssignment_1_0_2(), "rule__SubqueryFromClause__FieldAccessExpressionAssignment_1_0_2");
					put(grammarAccess.getSubqueryFromClauseAccess().getCandidateClassNameAssignment_1_1(), "rule__SubqueryFromClause__CandidateClassNameAssignment_1_1");
					put(grammarAccess.getSubqueryFromClauseAccess().getAliasAssignment_2(), "rule__SubqueryFromClause__AliasAssignment_2");
					put(grammarAccess.getSubqueryFromClauseAccess().getIsExcludeSubclassesAssignment_3_0(), "rule__SubqueryFromClause__IsExcludeSubclassesAssignment_3_0");
					put(grammarAccess.getAliasAccess().getIdentifierAssignment_1(), "rule__Alias__IdentifierAssignment_1");
					put(grammarAccess.getWhereClauseAccess().getFilterAssignment_1(), "rule__WhereClause__FilterAssignment_1");
					put(grammarAccess.getVariablesClauseAccess().getVariableDeclarationsAssignment_1(), "rule__VariablesClause__VariableDeclarationsAssignment_1");
					put(grammarAccess.getVariablesClauseAccess().getVariableDeclarationsAssignment_2_1(), "rule__VariablesClause__VariableDeclarationsAssignment_2_1");
					put(grammarAccess.getVariableDeclarationAccess().getTypeAssignment_0(), "rule__VariableDeclaration__TypeAssignment_0");
					put(grammarAccess.getVariableDeclarationAccess().getVariableNameAssignment_1(), "rule__VariableDeclaration__VariableNameAssignment_1");
					put(grammarAccess.getParametersClauseAccess().getParameterDeclarationsAssignment_1(), "rule__ParametersClause__ParameterDeclarationsAssignment_1");
					put(grammarAccess.getParametersClauseAccess().getParameterDeclarationsAssignment_2_1(), "rule__ParametersClause__ParameterDeclarationsAssignment_2_1");
					put(grammarAccess.getParameterDeclarationAccess().getTypeAssignment_0(), "rule__ParameterDeclaration__TypeAssignment_0");
					put(grammarAccess.getParameterDeclarationAccess().getDeclaredParameterNameAssignment_1(), "rule__ParameterDeclaration__DeclaredParameterNameAssignment_1");
					put(grammarAccess.getImportClauseAccess().getImportDeclarationsAssignment_0(), "rule__ImportClause__ImportDeclarationsAssignment_0");
					put(grammarAccess.getImportClauseAccess().getImportDeclarationsAssignment_1_1(), "rule__ImportClause__ImportDeclarationsAssignment_1_1");
					put(grammarAccess.getGroupByClauseAccess().getGroupingAssignment_2(), "rule__GroupByClause__GroupingAssignment_2");
					put(grammarAccess.getGroupByClauseAccess().getGroupingAssignment_3_1(), "rule__GroupByClause__GroupingAssignment_3_1");
					put(grammarAccess.getGroupByClauseAccess().getHavingClauseAssignment_5(), "rule__GroupByClause__HavingClauseAssignment_5");
					put(grammarAccess.getHavingClauseAccess().getHavingAssignment_1(), "rule__HavingClause__HavingAssignment_1");
					put(grammarAccess.getOrderByClauseAccess().getOrderingAssignment_2(), "rule__OrderByClause__OrderingAssignment_2");
					put(grammarAccess.getOrderByClauseAccess().getOrderingAssignment_3_1(), "rule__OrderByClause__OrderingAssignment_3_1");
					put(grammarAccess.getOrderBySpecAccess().getDirectionAssignment_1(), "rule__OrderBySpec__DirectionAssignment_1");
					put(grammarAccess.getRangeClauseAccess().getStartAssignment_1(), "rule__RangeClause__StartAssignment_1");
					put(grammarAccess.getRangeClauseAccess().getEndAssignment_3(), "rule__RangeClause__EndAssignment_3");
					put(grammarAccess.getConditionalOrExpressionAccess().getRightAssignment_1_2(), "rule__ConditionalOrExpression__RightAssignment_1_2");
					put(grammarAccess.getConditionalAndExpressionAccess().getRightAssignment_1_2(), "rule__ConditionalAndExpression__RightAssignment_1_2");
					put(grammarAccess.getSimpleOrExpressionAccess().getRightAssignment_1_2(), "rule__SimpleOrExpression__RightAssignment_1_2");
					put(grammarAccess.getSimpleAndExpressionAccess().getRightAssignment_1_2(), "rule__SimpleAndExpression__RightAssignment_1_2");
					put(grammarAccess.getComparisonOperatorExpressionAccess().getOperatorAssignment_1_1(), "rule__ComparisonOperatorExpression__OperatorAssignment_1_1");
					put(grammarAccess.getComparisonOperatorExpressionAccess().getRightAssignment_1_2(), "rule__ComparisonOperatorExpression__RightAssignment_1_2");
					put(grammarAccess.getAdditionExpressionAccess().getOperatorAssignment_1_1(), "rule__AdditionExpression__OperatorAssignment_1_1");
					put(grammarAccess.getAdditionExpressionAccess().getRightAssignment_1_2(), "rule__AdditionExpression__RightAssignment_1_2");
					put(grammarAccess.getMultiplicationExpressionAccess().getOperatorAssignment_1_1(), "rule__MultiplicationExpression__OperatorAssignment_1_1");
					put(grammarAccess.getMultiplicationExpressionAccess().getRightAssignment_1_2(), "rule__MultiplicationExpression__RightAssignment_1_2");
					put(grammarAccess.getUnaryExpressionAccess().getCastTypeAssignment_0_1(), "rule__UnaryExpression__CastTypeAssignment_0_1");
					put(grammarAccess.getUnaryExpressionAccess().getRightAssignment_0_3(), "rule__UnaryExpression__RightAssignment_0_3");
					put(grammarAccess.getUnaryExpressionAccess().getUnaryOperatorAssignment_1_0(), "rule__UnaryExpression__UnaryOperatorAssignment_1_0");
					put(grammarAccess.getUnaryExpressionAccess().getRightAssignment_1_1(), "rule__UnaryExpression__RightAssignment_1_1");
					put(grammarAccess.getFieldAccessExpressionAccess().getRightAssignment_1_1_2(), "rule__FieldAccessExpression__RightAssignment_1_1_2");
					put(grammarAccess.getParameterOrFieldOrMethodExpressionAccess().getLiteralAssignment_0(), "rule__ParameterOrFieldOrMethodExpression__LiteralAssignment_0");
					put(grammarAccess.getParameterOrFieldOrMethodExpressionAccess().getThisAssignment_1(), "rule__ParameterOrFieldOrMethodExpression__ThisAssignment_1");
					put(grammarAccess.getParameterOrFieldOrMethodExpressionAccess().getIdAssignment_2(), "rule__ParameterOrFieldOrMethodExpression__IdAssignment_2");
					put(grammarAccess.getParameterOrFieldOrMethodExpressionAccess().getParameterNameAssignment_3_1(), "rule__ParameterOrFieldOrMethodExpression__ParameterNameAssignment_3_1");
					put(grammarAccess.getParameterOrFieldOrMethodExpressionAccess().getMethodAssignment_5(), "rule__ParameterOrFieldOrMethodExpression__MethodAssignment_5");
					put(grammarAccess.getFieldOrMethodExpressionAccess().getLiteralAssignment_0(), "rule__FieldOrMethodExpression__LiteralAssignment_0");
					put(grammarAccess.getFieldOrMethodExpressionAccess().getThisAssignment_1(), "rule__FieldOrMethodExpression__ThisAssignment_1");
					put(grammarAccess.getFieldOrMethodExpressionAccess().getIdAssignment_2(), "rule__FieldOrMethodExpression__IdAssignment_2");
					put(grammarAccess.getFieldOrMethodExpressionAccess().getMethodAssignment_4(), "rule__FieldOrMethodExpression__MethodAssignment_4");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_0_0(), "rule__StaticMethodExpression__NameAssignment_0_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_0_2(), "rule__StaticMethodExpression__NumberAssignment_0_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_1_0(), "rule__StaticMethodExpression__NameAssignment_1_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_1_2(), "rule__StaticMethodExpression__NumberAssignment_1_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_2_0(), "rule__StaticMethodExpression__NameAssignment_2_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_2_2(), "rule__StaticMethodExpression__NumberAssignment_2_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_3_0(), "rule__StaticMethodExpression__NameAssignment_3_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_3_2(), "rule__StaticMethodExpression__NumberAssignment_3_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_4_0(), "rule__StaticMethodExpression__NameAssignment_4_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_4_2(), "rule__StaticMethodExpression__NumberAssignment_4_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_5_0(), "rule__StaticMethodExpression__NameAssignment_5_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_5_2(), "rule__StaticMethodExpression__NumberAssignment_5_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_6_0(), "rule__StaticMethodExpression__NameAssignment_6_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_6_2(), "rule__StaticMethodExpression__NumberAssignment_6_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_7_0(), "rule__StaticMethodExpression__NameAssignment_7_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_7_2(), "rule__StaticMethodExpression__NumberAssignment_7_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_8_0(), "rule__StaticMethodExpression__NameAssignment_8_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_8_2(), "rule__StaticMethodExpression__NumberAssignment_8_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_9_0(), "rule__StaticMethodExpression__NameAssignment_9_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_9_2(), "rule__StaticMethodExpression__NumberAssignment_9_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_10_0(), "rule__StaticMethodExpression__NameAssignment_10_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_10_2(), "rule__StaticMethodExpression__NumberAssignment_10_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_11_0(), "rule__StaticMethodExpression__NameAssignment_11_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_11_2(), "rule__StaticMethodExpression__NumberAssignment_11_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_12_0(), "rule__StaticMethodExpression__NameAssignment_12_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_12_2(), "rule__StaticMethodExpression__NumberAssignment_12_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_13_0(), "rule__StaticMethodExpression__NameAssignment_13_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_13_2(), "rule__StaticMethodExpression__NumberAssignment_13_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_14_0(), "rule__StaticMethodExpression__NameAssignment_14_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_14_2(), "rule__StaticMethodExpression__NumberAssignment_14_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_15_0(), "rule__StaticMethodExpression__NameAssignment_15_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_15_2(), "rule__StaticMethodExpression__NumberAssignment_15_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_16_0(), "rule__StaticMethodExpression__NameAssignment_16_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_16_2(), "rule__StaticMethodExpression__NumberAssignment_16_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_17_0(), "rule__StaticMethodExpression__NameAssignment_17_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_17_2(), "rule__StaticMethodExpression__NumberAssignment_17_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_18_0(), "rule__StaticMethodExpression__NameAssignment_18_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_18_2(), "rule__StaticMethodExpression__NumberAssignment_18_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_19_0(), "rule__StaticMethodExpression__NameAssignment_19_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_19_2(), "rule__StaticMethodExpression__NumberAssignment_19_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_20_0(), "rule__StaticMethodExpression__NameAssignment_20_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_20_2(), "rule__StaticMethodExpression__NumberAssignment_20_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_21_0(), "rule__StaticMethodExpression__NameAssignment_21_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_21_2(), "rule__StaticMethodExpression__NumberAssignment_21_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_22_0(), "rule__StaticMethodExpression__NameAssignment_22_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_22_2(), "rule__StaticMethodExpression__NumberAssignment_22_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_23_0(), "rule__StaticMethodExpression__NameAssignment_23_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getNumberAssignment_23_2(), "rule__StaticMethodExpression__NumberAssignment_23_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_24_0(), "rule__StaticMethodExpression__NameAssignment_24_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getPersistableAssignment_24_2(), "rule__StaticMethodExpression__PersistableAssignment_24_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_25_0(), "rule__StaticMethodExpression__NameAssignment_25_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getPersistableAssignment_25_2(), "rule__StaticMethodExpression__PersistableAssignment_25_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_26_0(), "rule__StaticMethodExpression__NameAssignment_26_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getPersistableAssignment_26_2(), "rule__StaticMethodExpression__PersistableAssignment_26_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_27_0(), "rule__StaticMethodExpression__NameAssignment_27_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getPersistableAssignment_27_2(), "rule__StaticMethodExpression__PersistableAssignment_27_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_28_0(), "rule__StaticMethodExpression__NameAssignment_28_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getIsDistinctAssignment_28_2(), "rule__StaticMethodExpression__IsDistinctAssignment_28_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getAggregateArgumentAssignment_28_3(), "rule__StaticMethodExpression__AggregateArgumentAssignment_28_3");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_29_0(), "rule__StaticMethodExpression__NameAssignment_29_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getIsDistinctAssignment_29_2(), "rule__StaticMethodExpression__IsDistinctAssignment_29_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getAggregateArgumentAssignment_29_3(), "rule__StaticMethodExpression__AggregateArgumentAssignment_29_3");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_30_0(), "rule__StaticMethodExpression__NameAssignment_30_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getAggregateArgumentAssignment_30_2(), "rule__StaticMethodExpression__AggregateArgumentAssignment_30_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_31_0(), "rule__StaticMethodExpression__NameAssignment_31_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getAggregateArgumentAssignment_31_2(), "rule__StaticMethodExpression__AggregateArgumentAssignment_31_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getNameAssignment_32_0(), "rule__StaticMethodExpression__NameAssignment_32_0");
					put(grammarAccess.getStaticMethodExpressionAccess().getIsDistinctAssignment_32_2(), "rule__StaticMethodExpression__IsDistinctAssignment_32_2");
					put(grammarAccess.getStaticMethodExpressionAccess().getAggregateArgumentAssignment_32_3(), "rule__StaticMethodExpression__AggregateArgumentAssignment_32_3");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_0_0(), "rule__MethodExpression__NameAssignment_0_0");
					put(grammarAccess.getMethodExpressionAccess().getElementAssignment_0_2(), "rule__MethodExpression__ElementAssignment_0_2");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_1_0(), "rule__MethodExpression__NameAssignment_1_0");
					put(grammarAccess.getMethodExpressionAccess().getArgAssignment_1_2(), "rule__MethodExpression__ArgAssignment_1_2");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_2_0(), "rule__MethodExpression__NameAssignment_2_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_3_0(), "rule__MethodExpression__NameAssignment_3_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_4_0(), "rule__MethodExpression__NameAssignment_4_0");
					put(grammarAccess.getMethodExpressionAccess().getKeyAssignment_4_2(), "rule__MethodExpression__KeyAssignment_4_2");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_5_0(), "rule__MethodExpression__NameAssignment_5_0");
					put(grammarAccess.getMethodExpressionAccess().getValueAssignment_5_2(), "rule__MethodExpression__ValueAssignment_5_2");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_6_0(), "rule__MethodExpression__NameAssignment_6_0");
					put(grammarAccess.getMethodExpressionAccess().getKeyAssignment_6_2(), "rule__MethodExpression__KeyAssignment_6_2");
					put(grammarAccess.getMethodExpressionAccess().getValueAssignment_6_4(), "rule__MethodExpression__ValueAssignment_6_4");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_7_0(), "rule__MethodExpression__NameAssignment_7_0");
					put(grammarAccess.getMethodExpressionAccess().getIndexAssignment_7_2(), "rule__MethodExpression__IndexAssignment_7_2");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_8_0(), "rule__MethodExpression__NameAssignment_8_0");
					put(grammarAccess.getMethodExpressionAccess().getStringAssignment_8_2(), "rule__MethodExpression__StringAssignment_8_2");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_9_0(), "rule__MethodExpression__NameAssignment_9_0");
					put(grammarAccess.getMethodExpressionAccess().getStringAssignment_9_2(), "rule__MethodExpression__StringAssignment_9_2");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_10_0(), "rule__MethodExpression__NameAssignment_10_0");
					put(grammarAccess.getMethodExpressionAccess().getStringAssignment_10_2(), "rule__MethodExpression__StringAssignment_10_2");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_11_0(), "rule__MethodExpression__NameAssignment_11_0");
					put(grammarAccess.getMethodExpressionAccess().getStringAssignment_11_2(), "rule__MethodExpression__StringAssignment_11_2");
					put(grammarAccess.getMethodExpressionAccess().getFromIndexAssignment_11_3_1(), "rule__MethodExpression__FromIndexAssignment_11_3_1");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_12_0(), "rule__MethodExpression__NameAssignment_12_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_13_0(), "rule__MethodExpression__NameAssignment_13_0");
					put(grammarAccess.getMethodExpressionAccess().getRegexAssignment_13_2(), "rule__MethodExpression__RegexAssignment_13_2");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_14_0(), "rule__MethodExpression__NameAssignment_14_0");
					put(grammarAccess.getMethodExpressionAccess().getRegexAssignment_14_2(), "rule__MethodExpression__RegexAssignment_14_2");
					put(grammarAccess.getMethodExpressionAccess().getReplacementAssignment_14_4(), "rule__MethodExpression__ReplacementAssignment_14_4");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_15_0(), "rule__MethodExpression__NameAssignment_15_0");
					put(grammarAccess.getMethodExpressionAccess().getStringAssignment_15_2(), "rule__MethodExpression__StringAssignment_15_2");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_16_0(), "rule__MethodExpression__NameAssignment_16_0");
					put(grammarAccess.getMethodExpressionAccess().getBeginIndexAssignment_16_2(), "rule__MethodExpression__BeginIndexAssignment_16_2");
					put(grammarAccess.getMethodExpressionAccess().getEndIndexAssignment_16_3_1(), "rule__MethodExpression__EndIndexAssignment_16_3_1");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_17_0(), "rule__MethodExpression__NameAssignment_17_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_18_0(), "rule__MethodExpression__NameAssignment_18_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_19_0(), "rule__MethodExpression__NameAssignment_19_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_20_0(), "rule__MethodExpression__NameAssignment_20_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_21_0(), "rule__MethodExpression__NameAssignment_21_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_22_0(), "rule__MethodExpression__NameAssignment_22_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_23_0(), "rule__MethodExpression__NameAssignment_23_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_24_0(), "rule__MethodExpression__NameAssignment_24_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_25_0(), "rule__MethodExpression__NameAssignment_25_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_26_0(), "rule__MethodExpression__NameAssignment_26_0");
					put(grammarAccess.getMethodExpressionAccess().getNameAssignment_27_0(), "rule__MethodExpression__NameAssignment_27_0");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.nightlabs.vestigo.xtext.jdoql.ui.contentassist.antlr.internal.InternalJDOQLParser typedParser = (org.nightlabs.vestigo.xtext.jdoql.ui.contentassist.antlr.internal.InternalJDOQLParser) parser;
			typedParser.entryRuleSingleStringJDOQL();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public JDOQLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JDOQLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
