/*
 * generated by Xtext
 */
package org.nightlabs.vestigo.xtext.jdoql.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.nightlabs.vestigo.xtext.jdoql.ui.internal.JDOQLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JDOQLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JDOQLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JDOQLActivator.getInstance().getInjector(JDOQLActivator.ORG_NIGHTLABS_VESTIGO_XTEXT_JDOQL_JDOQL);
	}
	
}
