<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jDOQL"
    nsURI="http://www.nightlabs.org/jjqb/xtext/jdoql/JDOQL" nsPrefix="jDOQL">
  <eClassifiers xsi:type="ecore:EClass" name="SingleStringJDOQL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="select" eType="#//Select"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//From" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//Where"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Select">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultClause" eType="#//ResultClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intoClause" eType="#//IntoClause"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultSpecs" upperBound="-1"
        eType="#//ResultSpecs" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntoClause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="From">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="candidateClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludeClause" eType="#//ExcludeClause"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Where">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="#//BooleanExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExcludeClause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludeSubclasses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultSpecs"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultSpec" eSuperTypes="#//ResultSpecs"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultNaming">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//ResultSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultNaming" eType="#//ResultNaming"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UnaryExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UnaryExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Primary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Primary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="this" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classOrInterface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
