/*
* generated by Xtext
*/
package org.nightlabs.jjqb.xtext.jpql.ui.contentassist;

import org.nightlabs.jjqb.xtext.jpql.ui.contentassist.AbstractJPQLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JPQLProposalProvider extends AbstractJPQLProposalProvider {

}
