/*
 * generated by Xtext
 */
package org.nightlabs.vestigo.xtext.jpql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JPQLUiModule extends org.nightlabs.vestigo.xtext.jpql.ui.AbstractJPQLUiModule {
	public JPQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
