/*
 * generated by Xtext
 */
package org.nightlabs.jjqb.xtext.jdoql.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JDOQLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.nightlabs.jjqb.xtext.jdoql.ui.internal.JDOQLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.nightlabs.jjqb.xtext.jdoql.ui.internal.JDOQLActivator.getInstance().getInjector("org.nightlabs.jjqb.xtext.jdoql.JDOQL");
	}
	
}
