/*
* generated by Xtext
*/
package org.nightlabs.vestigo.xtext.jpql;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JPQLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.nightlabs.vestigo.xtext.jpql.ui.internal.JPQLActivator.getInstance().getInjector("org.nightlabs.vestigo.xtext.jpql.JPQL");
	}
	
}
