/*
* generated by Xtext
*/
package org.nightlabs.jjqb.xtext.jdoql.ui.contentassist;

import org.eclipse.datatools.connectivity.IConnectionProfile;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.nightlabs.jjqb.ui.editor.QueryEditorManager;
import org.nightlabs.jjqb.ui.editor.DocumentContextManager;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JDOQLProposalProvider extends AbstractJDOQLProposalProvider {


	@Override
	public void complete_CandidateClassName(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {

		super.complete_CandidateClassName(model, ruleCall, context, acceptor);

		System.out.println("************* complete_CandidateClassName ***************");
		QueryEditorManager queryEditorManager = DocumentContextManager.sharedInstance().getQueryEditorManager(context.getDocument(), true);
		System.out.println("queryBrowserManager: " + queryEditorManager);
		IConnectionProfile connectionProfile = queryEditorManager.getConnectionProfile();
		// How to get my ConnectionProfile with my childVM?!
		System.out.println("connectionProfile: " + connectionProfile);
		System.out.println("************* complete_CandidateClassName ***************");

		String[] classes = new String[] {
				"org.nightlabs.Test1",
				"org.nightlabs.supadupa.Test2",
				"org.nightlabs.xxx.SuperClass"
		};
		for (String className : classes) {
			acceptor.accept(createCompletionProposal(className, context));
		}

	}

}
