/*
 * generated by Xtext
 */
package org.nightlabs.vestigo.xtext.jdoql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JDOQLUiModule extends org.nightlabs.vestigo.xtext.jdoql.ui.AbstractJDOQLUiModule {
	public JDOQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
