/*
* generated by Xtext
*/
package org.nightlabs.vestigo.xtext.jdoql;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JDOQLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.nightlabs.vestigo.xtext.jdoql.ui.internal.JDOQLActivator.getInstance().getInjector("org.nightlabs.vestigo.xtext.jdoql.JDOQL");
	}
	
}
