/*
* generated by Xtext
*/
package org.nightlabs.jjqb.xtext.jpql.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class JPQLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
