CREATE TABLE JDOSIMPLEENTITY (
  ID BIGINT NOT NULL, 
  PROPERTY VARCHAR(255) NOT NULL, 
  PRIMARY KEY (ID)
);
INSERT INTO JDOSIMPLEENTITY VALUES (1, 'A nice property');
INSERT INTO JDOSIMPLEENTITY VALUES (2, 'The second entity');
INSERT INTO JDOSIMPLEENTITY VALUES (3, 'Three');